### ISSUE TITLE
Error with exp calculation

### ISSUE THREAD

**Issue by WarnDa** [Zrips/TradeMeAddon#62]
[sourcelevel] and [targetlevel] are sometimes bugged.

I use : 
- Trademe 6.1.0.1
- CMILib 1.0.3.3
- Paper 1.16.5
(French langage but I'll translate for you)

Before the trade I was level 112 and player were level 19.

If I add some exp to the trade, the "ToggleButton" seems to work nice and show : 
<img width="434" alt="Screenshot_5468" src="https://user-images.githubusercontent.com/31826333/127941151-2df12ae9-2949-4bf8-8773-98bdabfa4659.png">
In config it's : 
Après l''échange vous serez lvl &f[sourcelevel]'
(meaning : after trade YOU will be level XX)
Après l''échange le joueur sera lvl &f[targetlevel]'
(meaning : after trade: player will be level XX)

But the "OfferedButton" shows : 
<img width="423" alt="Screenshot_5469" src="https://user-images.githubusercontent.com/31826333/127941211-98338083-a0b7-4f32-b603-97ab6720e8a4.png">
In config it's : 
Après l''échange vous serez lvl &f[sourcelevel]'
(meaning : after trade YOU will be level XX)
Après l''échange le joueur sera lvl &f[targetlevel]'
(meaning : after trade: player will be level XX)

But it doesn't display the good values at all.

**Comment by Zrips** [comment]
Exp isint linear when it comes to levels. Adding 19 (493exp) levels of exp to 112 (40468exp) will result into total experience of 40961 which translates into same 112levels with some additional exp on side. You can add [targetexp] variable to indicate how much of the extra exp you will have to be more clear whats going on, but just remember that higher levels require allot more exp to rise one level. So you are not trading levels, you are trading exp points. 
Other than this it could have been issue with offered button not updating properly, but that should have been fixed with latest build.

**Comment by WarnDa** [comment]
Update using LATEST RELEASE



I found the issue : 

If the two player trade EXP, it will only show YOUR BOTH levels but depending on the idea HE gives you,

so for example : 
- if the two player get 500exp before the trade,
- they add all their exp to the trade
- the two will we "you'll be level 0 and other player will be level 40" because it doesn't check the exp YOU give to the other player.

**Comment by Zrips** [comment]
Flushed out some inconsistencies when both players tries to trade exp, will post new version soon enough with those changes
