### ISSUE TITLE
Trade often fail

### ISSUE THREAD

**Issue by WarnDa** [Zrips/TradeMeAddon#65]
Trademe 6.1.0.3
Paper 1.16.5

Trade between player often fail (I got a message in the chat)
<img width="655" alt="Screenshot_6664" src="https://user-images.githubusercontent.com/31826333/137600947-d974e6d0-6a2f-4a8c-a466-6649ab6cc1a6.png">

I don't get much informations, but they don't try to dupe or anything else, just trade fail...

**Comment by WarnDa** [comment]
The message when it fails : 
https://cdn.discordapp.com/attachments/890510462960152616/899398934735229008/unknown.png

**Comment by Zrips** [comment]
This message appears when we have too many items in the trade. Could be caused by another plugin adding new items to players inventory while they are trading. This can cause issue with false positives where end item count doesn't match starting one and we are canceling trade to prevent item dupe. Do you have any plugin which would give out diamonds? As its indicating that there have been +5 diamonds

**Comment by WarnDa** [comment]
> Do you have any plugin which would give out diamonds? As its indicating that there have been +5 diamonds

I got no plugin that gives items.
So I don't know how they get items, but I often get this "fail issue"

**Comment by WarnDa** [comment]
Edit :

Sometimes player get more items (item on the floor that drop in their inventory), so it fails the trade.
But possible to disable theses check as it's not dupe ?

**Comment by WarnDa** [comment]
> Sometimes player get more items (item on the floor that drop in their inventory), so it fails the trade.
But possible to disable theses check as it's not dupe ?


Would be cool if it could be fixed, it's annoying for player, if they trade while there are items on the floor it fails the trade

**Comment by Zrips** [comment]
Adding option to disable exploit detection and/oritem reset which will resolve your issue here
