### ISSUE TITLE
Player can lose items in trade

### ISSUE THREAD

**Issue by WarnDa** [Zrips/TradeMeAddon#68]
I'm using latest Trademe and latest CMILib on paper 1.16.5

While you trade someone, if you got items dropped in your inventory, it fails the trade, and you lost the items that you received in inventory.

So it's why everytime a trade fail, but it shouldn't fail the trade.
If you detect that the "52 iron_ingot" where on the floor and I just pick up them on the floor, then the trade wouldn't fail

Video of the issue : 
https://youtu.be/65Kb7hxvGa4
On this video, when I trade, a player drop me 52 iron_ingot on the floor. So it fails the trade and I lost the 52 iron_ingot.

**Comment by Zrips** [comment]
In general players cant pick up items from ground while trade window is open, but there other means to get new items while trading with players, mainly caused by another plugin adding items directly into players inventory. You losing those items was a result of potential exploit detection when you had more items at trade end than you had at trade start.
Will add option to disable this with next update.
